### ISSUE TITLE
RDPC Portal Homepage - Hero

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/rdpc-ui#10]
## Goal
Build a static UI for homepage hero: 
![Screen Shot 2023-03-30 at 5.16.31 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/813f3c47-4873-46de-829a-ad536dd7d211)

Mockup: https://www.figma.com/file/O9jdbXSZMQf5F34OJAhyRT/ARGO-RPDC%3A-Exploration?type=design&node-id=96%3A66763&t=Qsydioj8CgnLCHvE-1

**Comment by ciaranschutte** [comment]
@Buwujiu "Back to ICGC ARGO" link goes back to platform?

**Comment by Buwujiu** [comment]
> @Buwujiu "Back to ICGC ARGO" link goes back to platform?

@ciaranschutte yes, it goes back to platform.

**Comment by Buwujiu** [comment]
> Do we have a list of RDPCs and associated flags yet?

@ciaranschutte No, we don't have signed RDPCs yet

**Comment by ciaranschutte** [comment]
not adding the region flag right now.

it's too much configurable to put into env var. we'd need to hard code images and then select based on the variable.

We need a bigger discussion on the practicalities of allow this configuration.

**Comment by Buwujiu** [comment]
Tested in QA, logged some feedbacks in https://github.com/icgc-argo/rdpc-ui/issues/49.
