### ISSUE TITLE
Build The Contact Page

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/rdpc-ui#13]
## Goal
Build a static contact page, the page can be accessed by clicking on `Contact` in the footer.
Refer to existing argo platform contact page as example: https://platform.icgc-argo.org/contact
![Screenshot 2023-06-05 at 10.50.43 AM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/f96435ff-3619-43ee-914a-b7af96f25b4d)

## Exit Criteria
1. UI should look exactly the same as the existing contact page in argo platform.
2. All links on the left side should point to argo doc site.
3. Users should be able to enter email address, name, messages, selecting a topic.
4. Do not implement the SEND MESSAGE button yet, we want the the receiver to be configurable.

**Comment by ciaranschutte** [comment]
in QA env, waiting on this PR merge for page to work

**Comment by Buwujiu** [comment]
Getting errors in QA, will require config changes.

**Comment by ciaranschutte** [comment]
still a config issue here
