### ISSUE TITLE
Add Login Button 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/rdpc-ui#4]
## Detailed Description
As part of building user login: https://github.com/icgc-argo/rdpc-ui/issues/7: 
1. Build the top right Login button.
2. Mockup: https://www.figma.com/file/O9jdbXSZMQf5F34OJAhyRT/ARGO-RPDC%3A-Exploration?type=design&node-id=96-66761

## Exit Criteria
There is a separate task for building the homepage, so for the scope of this ticket, just build 1 login button on the top right corner. No need to build the entire homepage.

**Comment by ciaranschutte** [comment]
@bhavikbhagat93  The status of this ticket appears stale as I'm working on feedback on the homepage related to the login button... So it's definitely been through QA
