### ISSUE TITLE
How to Configure The Region Flag on Homepage? 

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/rdpc-ui#50]
## Detailed Description
Followup task to https://github.com/icgc-argo/rdpc-ui/issues/10. 
Refer to comment: https://github.com/icgc-argo/rdpc-ui/issues/10#issuecomment-1620714509. 
Let's investigate what would be the best way to configure the region flags.

**Comment by bhavikbhagat93** [comment]
Note: Adding flag image has a technical overhead of hosting the flag image, Adding it to config and maintaining config versions for each RDPC. 

Can be added to future versions of RDPC if required. for MVP - more technical work.
