### ISSUE TITLE
RDPC Portal Homepage - Action Box and Overture Banner

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/rdpc-ui#9]
## Goal
Build static ui for homepage - action box and overture banner.
![Screen Shot 2023-03-30 at 5.18.35 PM.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/0f53df9d-7a6a-4677-8c24-a28f874a1d75)

Links:
1. HOW TO APPLY: https://docs.icgc-argo.org/docs/data-access/daco/applying
2. DATA SUBMISSION GUIDE: https://docs.icgc-argo.org/docs/submission/submission-overview
3. ABOUT OUR WORKFLOWS: https://docs.icgc-argo.org/docs/analysis-workflows/analysis-overview

**Comment by ciaranschutte** [comment]
Can I get the urls to link out please?

**Comment by Buwujiu** [comment]
Tested in QA, logged some feedbacks in https://github.com/icgc-argo/rdpc-ui/issues/49.
